rules:
  max-ten:
    max: 6
  max-kanji-continuous-len:
    max: 6
    allow:
      - 鳥取県東伯郡琴浦町槻下
      - 鳥取県中西部
  no-doubled-joshi:
    min_interval: 1
    strict: false
    allow: ["も", "や", "たり"]
  no-hankaku-kana: true
  ja-no-redundant-expression: true
  no-mixed-zenkaku-and-hankaku-alphabet: true
  sentence-length:
    max: 150
  first-sentence-length:
    max: 80
  no-dropping-the-ra: true
  no-doubled-conjunctive-particle-ga: true
  no-doubled-conjunction: true
  ja-no-mixed-period: true
  textlint-rule-max-length-of-title:
    '#': 25
    '##': 30
  ja-hiragana-keishikimeishi: true
  ja-hiragana-fukushi: true
  ja-space-between-half-and-full-width:
    space: always
  ja-nakaguro-or-halfwidth-space-between-katakana: true
