# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: node:11.10.1
        environment:
          TZ: '/usr/share/zoneinfo/Asia/Tokyo'
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
            echo "$(git --version)"
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ./node_modules
            - ~/.cache/yarn/
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Validate
          command: yarn validate
      - run:
          name: Test
          command: yarn test
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - deploy:
          name: Deploy to gh-pages
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              git config --global user.email "${DEPLOYMENT_GITHUB_USER_EMAIL}"
              git config --global user.name "${DEPLOYMENT_GITHUB_USER_NAME}"
              yarn deploy
            fi
